function c0_window(btn,BOB)

newwin=uifigure('Name','Continuum limit comparison',...
                'WindowStyle','modal',...
                'Position',[250,700,500,500]);
%{
split_win=uigridlayout(newwin,[2,1],...
                    'RowHeight',{'1x','1x'},...
                    'ColumnWidth', {'1x'});
%}
                %'RowSpacing',0,...
             %        'ColumnSpacing',0,...
                   %   'Padding',[1,1,1,1])
grph_pan=uipanel(newwin,'Position',[0,100,500,425]);

%grph_pan.Layout.Row=1;
%grph_pan.Layout.Column=1;
sld_pan=uipanel(newwin,'Position',[0,0,500,75]);
sld_pan.Tag='g2pan';
%sld_pan.Layout.Row=2;
%sld_pan.Layout.Column=1;
grph_pan_dim=get(grph_pan,'Position');
c0_ax=uiaxes(grph_pan,'xlim',[0,1],...
    'ylim',[0.2,1.1],...
    'xticklabel',[],...
    'Position',[0.1*grph_pan_dim(3),0,400,375]);
    c0_ax.XGrid='on';
    c0_ax.YGrid='on';
    c0_ax.Box='on';
    c0_ax.NextPlot='add';
init_sld=30;
sld_pan_dim=get(sld_pan,'Position');

itog_convert=4.+ 0.1*([1:3:61]-1);
c0_sld=uislider(sld_pan,'Position', [0.02*sld_pan_dim(3),0.5*sld_pan_dim(4),0.96*sld_pan_dim(3),25],...
                'Value',init_sld,...   
                'ValueChangedFcn',@(sldr,event) c0_sldr(sldr,c0_ax,BOB),...
                'Limits', [1,61],...
                'MajorTicks',[1:3:61],...
                'MajorTickLabels', categorical(string(itog_convert)));

end